default: driver

driver: driver.c
	gcc driver.c -o driver -lftdi1

clean:
	rm -rf impl
	rm -rf *.dir
	rm -f driver
	rm -f .recovery
	rm -f .*.ini
	rm -f *.html
	rm -f *.xml
	rm -f *.ccl
	rm -f *.log
	rm -f *.tpf
	rm -f *.htm
